steps:

- id: "Copiando .env"
  name: "bash"
  args: ['cp' , '.env.example', '.env']

- id: "Criando pasta host"
  name: "bash"
  args: ["mkdir", "-p", "/var/www/html"]

- id: "Ajuste de permissão da pasta 1"
  name: "bash"
  args: ["chmod", "-R", "775", "/var/www/html"]

- id: "Ajuste de permissão da pasta 2"
  name: "bash"
  args: ["chown", "-R", "$USER:$USER", "/var/www/html"]

- id: "Rodando docker-compose"
  name: "gcr.io/$PROJECT_ID/docker-compose"
  args: ['-f', 'docker-compose.cloudbuild.yml', 'up', '-d']

- id: "Rodando docker ps"
  name: "gcr.io/cloud-builders/docker"
  args: ['ps']

- id: "Rodando composer"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'dlh_php_1', 'composer', 'install']

- id: "Rodando key:generate"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'dlh_php_1', 'php' , '/var/www/html/artisan', 'key:generate']
