steps:

- id: "Copiando .env"
  name: "bash"
  args: ['cp' , '.env.example', '.env']

- id: "Rodando docker-compose"
  name: "docker/compose"
  args: ['up', '-d']

- id: "Chown in /var/www"
  name: 'docker'
  args: [ 'exec','-u','root','-t','dlh_php_1','chown','-R','www-data:www-data','/var/www' ]

- id: "Rodando composer"
  name: "docker"
  args: ['exec', '-t', 'dlh_php_1', 'composer', 'install']

- id: "Rodando key:generate"
  name: "docker"
  args: ['exec', '-t', 'dlh_php_1', 'php' , '/var/www/html/artisan', 'key:generate']

- id: "Rodando migrations"
  name: "docker"
  args: ['exec', '-t', 'dlh_php_1', 'php' , '/var/www/html/artisan', 'migrate']

- id: "Rodando php unit"
  name: "docker"
  args: ['exec', '-t', 'dlh_php_1', 'php' , '/var/www/html/vendor/bin/phpunit', '-c', '/var/www/html/phpunit.xml']
