version: "3.7"

services:

  go:
    container_name: desafio_ci_go
    build:
      context: .
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./src:/go/src/app